// <auto-generated />
using System;
using Facturacion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Facturacion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FacturacionDbContext))]
    [Migration("20260711210901_AgregarMetodoPagoYActividadEconomica")]
    partial class AgregarMetodoPagoYActividadEconomica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Facturacion.Domain.Entities.CredencialSiat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cufd")
                        .HasColumnType("text");

                    b.Property<string>("CufdCodigoControl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CufdVence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CuisVence")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PuntoVentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenDelegadoCifrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CredencialesSiat", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodigoProductoSin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoDescuento")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("DetallesFactura", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CodigoDocumentoSector")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoMetodoPago")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoMoneda")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoMotivoAnulacion")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoRecepcionSin")
                        .HasColumnType("text");

                    b.Property<int>("CodigoTipoDocumentoIdentidad")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuf")
                        .HasColumnType("text");

                    b.Property<string>("EmailComprador")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontoTotalSujetoIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumentoComprador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NumeroFactura")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumeroTarjeta")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PuntoVentaId")
                        .HasColumnType("uuid");

                    b.Property<string>("RazonSocialComprador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RespuestaSinRaw")
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TipoCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Estado");

                    b.HasIndex("TenantId", "ReferenciaExterna")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.PuntoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CodigoSiat")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoPuntoVenta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("PuntosVenta", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActividadEconomica")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CodigoSiat")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Facturacion.Infrastructure.Persistence.PuntoVentaCorrelativo", b =>
                {
                    b.Property<Guid>("PuntoVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint");

                    b.HasKey("PuntoVentaId");

                    b.ToTable("PuntoVentaCorrelativos", (string)null);
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Factura", null)
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.PuntoVenta", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Sucursal", null)
                        .WithMany("PuntosVenta")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("Facturacion.Domain.Entities.Tenant", null)
                        .WithMany("Sucursales")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("PuntosVenta");
                });

            modelBuilder.Entity("Facturacion.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
